#!/usr/bin/env bash
# Install and configure Nginx to return "Holberton School" at the root

set -e

# Update and install Nginx
apt-get update -y
apt-get install -y nginx

# Start Nginx
service nginx start

# Add content to default page
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Restart Nginx
service nginx restart
